server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  data:
    mongodb:
      database: catalog
      port: 27017
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
    instances:
      series:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '40'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
      movies:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '40'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
  resilience4j.retry:
    instances:
      series:
        maxAttempts: '3'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError
      movies:
        maxAttempts: '3'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError