server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-movie
  cloud:
    config:
      url: ${CONFIG_SERVER:http://localhost:8889}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev?createDatabaseIfNotExist=true
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/